select * from mytable limit 5;

-- Q1. what is the total revenue generated by men vs female customers?
select gender, sum(purchase_amount) as revenue
from mytable
group by gender

-- Q2. which customer used discount and still purchased more than an average purchase amaount? 
select customer_id, purchase_amount
from mytable
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from mytable)

-- Q3.Which are the top 5 products with the higest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS `Average Product Rating`
FROM mytable
GROUP BY item_purchased
ORDER BY `Average Product Rating` DESC
LIMIT 5;

-- Q4.Compare the average purchase amounts between standard and express shipping.
select shipping_type,
round(avg(cast(purchase_amount as decimal(10,2))),2) as 'Express VS Standard' 
from mytable
where shipping_type in ('standard','Express')
group by shipping_type

-- Q5. Do Subcribed customers spend more? Compare average spend and total revenue between subcribers and non-subcribers
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(CAST(purchase_amount AS DECIMAL(10,2))), 2) AS avg_spend,
    ROUND(SUM(CAST(purchase_amount AS DECIMAL(10,2))), 2) AS total_revenue
FROM mytable
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100 *sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*),2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. segment customers into new, returning, and loyal based on their total number of previous purchases and slow the count of each segment.
with customer_type as (
select customer_id, previous_purchases, 
case
    when previous_purchases = 1 then 'new'
    when previous_purchases between 2 and 10 then 'returning'
    else 'loyal'
    end as customer_segment
from mytable
)

select customer_segment,count(*) as "number of customers"
from customer_type
group by customer_segment

-- Q8. what are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category ordeR by count(customer_id) desc) as item_rank
from mytable
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

Q9. What is the revenue who are repeat buyers (more than 5 previous purchases) also likely to subcribe?
select subscription_status,
count(customer_id) as repeat_buyers
from mytable 
where previous_purchases > 5
group by subscription_status

-- Q10. what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from mytable
group by age_group
order by total_revenue desc;
